model = "gpt-5.5"
model_reasoning_effort = "high"
personality = "pragmatic"
project_doc_fallback_filenames = ["CLAUDE.md", "Claude.md"]

[projects."/Users/kkato"]
trust_level = "untrusted"

[projects."/Users/kkato/ghq/github.com/kkato/gin-fleamarket"]
trust_level = "trusted"

[projects."/Users/kkato/ghq/github.com/kkato/book-api"]
trust_level = "trusted"

[projects."/Users/kkato/ghq/github.com/kkato/blog-hugo"]
trust_level = "trusted"

[projects."/Users/kkato/ghq/github.com/kkato/k8s"]
trust_level = "trusted"

[projects."/Users/kkato/ghq/github.com/kkato/dotfiles"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"

[plugins."github@openai-curated"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 1
